---
- name: Install apt-transport-https and ca-certicates
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    state: present
  become: true

- name: Install Microsoft GPG key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: true

- name: Add Microsoft Visual Studio Code Repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: yes
  become: true

- name: Install Visual Studio Code including dependencies
  apt:
    name: ['libgtk2.0-0', 'libxss1', 'libx11-xcb1', 'libasound2', 'code']
    update_cache: true
  become: True
