---
- include_tasks: "debian.yml"
  when: ansible_os_family == "Debian"
- include_tasks: "redhat.yml"
  when: ansible_os_family == "RedHat" and not ansible_distribution == "Fedora"
  become: True
- include_tasks: "fedora.yml"
  when: ansible_distribution == "Fedora"
  become: True
- include_tasks: "suse.yml"
  when: ansible_os_family == "Suse"
  become: True
- include_tasks: install_extensions.yml
  when: vscode_extensions is defined
