---
- name: Add Microsoft Visual Studio Code repository
  yum_repository:
    name: vscode
    description: vscode
    file: vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: True
    baseurl: https://packages.microsoft.com/yumrepos/vscode
  become: True

- name: Install Visual Studio Code including dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - which
    - code
  become: True
