---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_xenial
    image: ubuntu:16.04
  - name: ubuntu_artful
    image: ubuntu:17.10
  - name: centos_7
    image: centos:7
  - name: fedora_27
    image: fedora:27
  - name: opensuse_leap
    image: opensuse:leap
  - name: opensuse_tumbleweed
    image: opensuse:tumbleweed

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        users_groups:
          - name: users
        users:
          - name: molecule
            group: users
          - name: molecule2
            group: users
        vscode_extensions:
          - user: molecule
            extensions:
              - vscodevim.vim
          - user: molecule2
            extensions:
              - ms-python.python
              - vscodevim.vim
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
