---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_latest
    image: ubuntu:latest
  - name: ubuntu_rolling
    image: ubuntu:rolling
  - name: centos_7
    image: centos:7

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        users_groups:
          - name: users
        users:
          - name: molecule
            group: users
          - name: molecule2
            group: users
        vscode_extensions:
          - user: molecule
            extensions:
              - vscodevim.vim
          - user: molecule2
            extensions:
              - ms-python.python
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
