---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_xenial
    image: ubuntu
    image_version: 16.04
  - name: ubuntu_zesty
    image: ubuntu
    image_version: 17.04
  - name: ubuntu_artful
    image: ubuntu
    image_version: 17.10
  - name: centos_7
    image: centos
    image_version: 7
  - name: fedora_25
    image: fedora
    image_version: 25
  - name: fedora_26
    image: fedora
    image_version: 26
  - name: opensuse_leap
    image: opensuse
    image_version: leap
  - name: opensuse_tumbleweed
    image: opensuse
    image_version: tumbleweed

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
